---
title: "Scales - JAT - Línea Final Mentores 25-26"
format:
    docx:
        df-print: kable
        fig-format: png
        out-widht: 80%
        fig-dpi: 300 
execute: 
  echo: false
  warning: false
theme: journal
---

```{r setup}
library(tidyverse)

output_path <- "output/mentores 25-26"

lb_scales <- read_rds(paste0(output_path, "/lb-scales-mentores-25-26.rds"))
lb_items <- read_rds(paste0(
    output_path,
    "/lb-psychometrics-mentores-25-26.rds"
))
lb_summary <- read_rds(paste0(output_path, "/lb-statistics-mentores-25-26.rds"))

lf_items <- read_rds(paste0(
    output_path,
    "/lf-psychometrics-mentores-25-26.rds"
))
lf_summary <- read_rds(paste0(output_path, "/lf-statistics-mentores-25-26.rds"))

grupos <- c(
    "nacional" = "nacional",
    "sexo" = "sexo",
    "edad" = "edad",
    "estado" = "estado",
    "sede" = "sede"
)

escalas <- c(
    "agnc" = "agnc",
    "team" = "team",
    "lead" = "lead",
    "empt" = "empt",
    "dcsn" = "dcsn"
)

comp_summary <-
    map(grupos, function(grupo_x) {
        inner_join(
            map_df(lb_summary, grupo_x),
            map_df(lf_summary, grupo_x),
            by = c("Scale", stringr::str_to_title(grupo_x)),
            suffix = c("_lb", "_lf")
        ) %>%
            select(-starts_with("Type")) %>%
            mutate(Diferencia = Mean_lf - Mean_lb) %>%
            select(
                all_of(c("Scale", stringr::str_to_title(grupo_x))),
                starts_with("Mean"),
                all_of("Diferencia"),
                starts_with("Sd"),
                starts_with("Se"),
                starts_with("N")
            )
    })

comp_item <- 
  map(escalas, function(escala_x) {
    inner_join(
        lb_items[[escala_x]],
        lf_items[[escala_x]],
        by = "item",
        suffix = c("_lb", "_lf")
    ) %>%
        mutate(diferencia = mean_lf - mean_lb) %>%
        select(
            all_of(
                c("item")
            ),
            starts_with("mean"),
            all_of("diferencia"),
            starts_with("sd"),
            starts_with("alpha_l"),
            starts_with("n")
        )
})

claves <- 
  lb_scales %>% 
  reduce(bind_rows) %>% 
  distinct(scale, number, question) %>% 
  mutate(number = stringr::str_pad(number, width = 2, pad = "0")) %>% 
  tidyr::unite("Item", scale, number, remove = FALSE) %>% 
  select("Scale" = "scale", "Item", "Question" = "question") %>% 
  distinct() %>% 
  arrange(Item)
```

## Nacional 

```{r}
comp_summary[["nacional"]]
```
{{< pagebreak >}}

## Sexo

```{r}
comp_summary[["sexo"]]
```
{{< pagebreak >}}

## Edad

```{r}
comp_summary[["edad"]]
```
{{< pagebreak >}}

## Estado

```{r}
comp_summary[["estado"]]
```
{{< pagebreak >}}

## Sede

```{r}
comp_summary[["sede"]]
```
{{< pagebreak >}}

## Agency

```{r}
comp_item[["agnc"]] %>% 
    arrange(item)
```
\
```{r}
claves %>% 
    filter(Scale == "Agency") %>% 
    select(-Scale)
```
{{< pagebreak >}}

## Teamwork

```{r}
comp_item[["team"]] %>% 
    arrange(item)
```
\
```{r}
claves %>% 
    filter(Scale == "Teamwork") %>% 
    select(-Scale)
```
{{< pagebreak >}}

## Leadership

```{r}
comp_item[["lead"]] %>% 
    arrange(item)
```
\
```{r}
claves %>% 
    filter(Scale == "Leadership") %>% 
    select(-Scale)
```
{{< pagebreak >}}

## Empathy

```{r}
comp_item[["empt"]] %>% 
    arrange(item)
```
\
```{r}
claves %>% 
    filter(Scale == "Empathy") %>% 
    select(-Scale)
```
{{< pagebreak >}}

## Decision

```{r}
comp_item[["dcsn"]] %>% 
    arrange(item)
```
\
```{r}
claves %>% 
    filter(Scale == "Decision") %>% 
    select(-Scale)
```
{{< pagebreak >}}
