---
title: "Agency - JAT - Base Mentores 25-26"
format:
    pdf:
        df-print: kable
        fig-format: png
        out-widht: 80%
        fig-dpi: 300 
    docx:
        df-print: kable
        fig-format: png
        out-widht: 80%
        fig-dpi: 300
engine: knitr
execute: 
  echo: false
  warning: false
theme: journal
---

```{r setup}
library(tidyverse)
library(mirt)

to_round_tibble <- function(x_df, decimals = 2)
{
  x_df %>%
    as_tibble() %>%
    mutate(across(where(is.numeric), ~ round(.x, decimals)))
}

item_stats <- read_rds("data/item_stats.rds")
item_irt <- read_rds("data/item_irt.rds")

irt_coefs <-
  map_df(item_irt, function(x) {
    coef(x$modelo, simplify = TRUE)$items %>%
      as.data.frame() %>%
      rownames_to_column("item")
  })

agencia <- item_stats$agencia
```

## Item stats
```{r overall}
as_tibble(agencia$overall) %>%
  mutate(across(where(is.numeric), ~ round(.x, 2)))
```

```{r item_stats}
agencia$itemstats %>% 
    as.data.frame() %>% 
    rownames_to_column("Item") %>% 
    to_round_tibble()
```

```{r proportions}
agencia$proportions %>% 
    as.data.frame() %>% 
    `names<-`(c("1", "2", "3", "4", "NA")) %>% 
    rownames_to_column("Item") %>% 
    to_round_tibble()
```

## IRT Coefficients
```{r irt_coefs}
irt_coefs %>%
  filter(stringr::str_detect(item, "agencia")) %>%
  mutate(
    across(where(is.numeric), ~ round(.x, 4))
  ) %>%
  select(-c)
```

```{r plot_coefs}
#| fig-width: 6
#| fig-height: 4
irt_coefs %>%
  filter(str_detect(item, "agencia")) %>%
  pivot_longer(
    cols = starts_with("b"),
    names_to = "threshold",
    values_to = "logits"
  ) %>%
  ggplot() +
  aes(item, logits, color = threshold) +
  geom_hline(yintercept = 0, alpha = .35) +
  geom_point() +
  scale_x_discrete(limits = rev) +
  scale_y_continuous(limits = c(-4, 4)) +
  scale_color_discrete(name = "Threshold") +
  labs(
    y = "Logits",
    x = "Items",
    subtitle = "Thresholds outside the range (-4, 4) are not shown"
  ) +
  coord_flip() +
  theme_bw() +
  theme(legend.position = "top")
```

## Score distribution
```{r score_distribution}
#| fig-width: 6
#| fig-height: 2
map_df(item_stats, "scores") %>%
  mutate(id = row_number()) %>%
  pivot_longer(-c("id"), names_to = "scale", values_to = "score") %>%
  filter(scale == "agencia") %>% 
  ggplot() +
  aes(score) +
  geom_vline(xintercept = 20, alpha = .25) +
  geom_density(aes(color = scale)) +
  labs(x = "Score", y = "Density") +
  facet_grid(rows = "scale") +
  theme_bw() +
  theme(legend.position = "none")
```

```{r score_distribution_irt}
#| fig-width: 6
#| fig-height: 2
map_df(item_irt, "scores") %>%
  mutate(id = row_number()) %>%
  pivot_longer(-c("id"), names_to = "scale", values_to = "score") %>%
    filter(scale == "agencia") %>% 
  ggplot() +
  aes(score) +
  geom_vline(xintercept = 0, alpha = .25) +
  geom_density(aes(color = scale)) +
  scale_x_continuous(limits = c(-4, 4)) +
  labs(x = "Logits", y = "Density") +
  facet_grid(rows = "scale") +
  theme_bw() +
  theme(legend.position = "none")
```

## Scale correlations
```{r scale_cors}
map_df(item_stats, "scores") %>%
  cor() %>%
  as.data.frame() %>%
  rownames_to_column("scale") %>%
  as_tibble() %>%
  mutate(across(where(is.numeric), ~ round(.x, 2)))
```