---
title: "JAT: Reporte seguimiento"
format: 
  html:
    df-print: kable
engine: knitr
execute: 
  echo: false
  warning: false
theme: journal
---

```{r Setup}
library(tidyverse)
library(arrow)
library(psych)

round_cols <- function(df_to_round) {
  df_to_round %>%
    mutate(across(where(is.numeric), ~ round(., 1)))
}

df_jat <- read_parquet("out/df_jat.parquet") %>%
  round_cols()
df_likert <- read_parquet("out/df_likert.parquet") %>%
  round_cols()
ls_qualitative <- read_rds("out/ls_qualitative.rds")
df_components <- read_parquet("out/df_components.parquet") %>%
  round_cols()
df_contact <- read_parquet("out/df_contact.parquet") %>%
  round_cols()

group_cols <- list(
  "General" = "general",
  "Estado" = "estado",
  "Género" = "sexo",
  "Estado y género" = c("estado", "sexo"),
  "Generación" = "periodo"
)
```

Total respondents: `r nrow(df_jat)`

## Gender distribution

```{r Gender distribution}
#| fig-width: 4
#| fig-height: 8
df_jat %>%
  count(sexo) %>%
  mutate(prop = round(n / sum(n) * 100, 1)) %>%
  set_names(c("Género", "N", "%"))
```

## State distribution

```{r State distribution}
#| fig-width: 4
#| fig-height: 8
df_jat %>%
  count(estado) %>%
  mutate(prop = round(n / sum(n) * 100, 1)) %>%
  set_names(c("Estado", "N", "%"))
```

## Gender by state distribution

```{r StatexGender distribution}
df_jat %>%
  count(estado, sexo) %>%
  group_by(estado) %>%
  mutate(prop = round(n / sum(n) * 100, 1)) %>%
  set_names(c("Estado", "Género", "N", "%"))
```

## Age

```{r age}
describe(df_jat["edad"])
```

## Education level

```{r Education}
df_jat %>%
  count(nivel_estudios, sort = TRUE) %>%
  mutate(prop = round(n / sum(n) * 100, 1)) %>%
  set_names(c("Nivel de estudios", "N", "%"))
```

## Ocupational status

```{r Ocupation}
df_jat %>%
  count(estatus_ocupacional, sexo, sort = TRUE) %>%
  mutate(prop = round(n / sum(n) * 100, 1)) %>%
  set_names(c("Nivel de estudios", "Género", "N", "%"))
```

## Likert

```{r likert}
df_likert
```

```{r}
df_jat %>%
  filter(periodo != "Otro") %>%
  select(periodo, matches("l.*?_num")) %>%
  group_by(periodo) %>%
  summarise(across(where(is.numeric), ~ mean(., na.rm = TRUE))) %>%
  pivot_longer(
    cols = starts_with("l"),
    names_to = "pregunta",
    values_to = "promedio"
  ) %>%
  mutate(
    pregunta = str_remove_all(pregunta, pattern = "l\\d_|_num") %>%
      str_replace_all("_", " ") %>%
      str_to_title()
  ) %>%
  ggplot() +
  aes(periodo, promedio, color = pregunta) +
  geom_hline(yintercept = 3, alpha = .3) +
  geom_point() +
  geom_line(aes(group = pregunta)) +
  scale_x_discrete(guide = guide_axis(angle = 90)) +
  labs(title = "Seguimiento de mentores", x = "Generación", y = "Puntaje promedio") +
  facet_wrap(pregunta~.) +
  theme_bw(base_size = 11) +
  theme(legend.position = "none")

```

```{r}
#| output: asis
map(group_cols, function(group_col) {
  df_jat %>%
    group_by(across(group_col)) %>%
    summarise(
      L1_mean = mean(l1_motivacion_estudiar_num, na.rm = TRUE),
      L5_mean = mean(l5_obstaculos_superados_num, na.rm = TRUE),
      Composite = mean(likert_total, na.rm = TRUE)
    ) %>%
    round_cols() %>%
    knitr::kable()
})
```

## Values
```{r Qualitative val general}
ls_qualitative[["val"]][["General"]] %>%
  rename_with(~ str_remove(., "_val"), ends_with("val")) %>%
  round_cols()
```

```{r Qualitative val state}
ls_qualitative[["val"]][["Estado"]] %>%
  rename_with(~ str_remove(., "_skill"), ends_with("val")) %>%
  round_cols()
```

```{r Qualitative val gender}
ls_qualitative[["val"]][["Género"]] %>%
  rename_with(~ str_remove(., "_skill"), ends_with("val")) %>%
  round_cols()
```

```{r Qualitative val state_gender}
ls_qualitative[["val"]][["Estado y género"]] %>%
  rename_with(~ str_remove(., "_skill"), ends_with("val")) %>%
  round_cols()
```

## Skills
```{r Qualitative skill general}
ls_qualitative[["skill"]][["General"]] %>%
  rename_with(~ str_remove(., "_skill"), ends_with("skill")) %>%
  round_cols()
```


```{r Qualitative skill state}
ls_qualitative[["skill"]][["Estado"]] %>%
  rename_with(~ str_remove(., "_skill"), ends_with("skill")) %>%
  round_cols()
```

```{r Qualitative skill gender}
ls_qualitative[["skill"]][["Género"]] %>%
  rename_with(~ str_remove(., "_skill"), ends_with("skill")) %>%
  round_cols()
```

```{r Qualitative skill state_gender}
ls_qualitative[["skill"]][["Estado y género"]] %>%
  rename_with(~ str_remove(., "_skill"), ends_with("skill")) %>%
  round_cols()
```

## Components
```{r Components}
df_components %>%
  round_cols()
```

## Contact
```{r Contact}
df_contact %>%
  round_cols()

```

## Positive experience
```{r}
df_jat %>%
  select(respondent_id, matches("^L\\d.*?(_num)")) %>%
  pivot_longer(cols = starts_with("L")) %>%
  na.omit() %>%
  mutate(positivo = value >= 3) %>%
  group_by(name) %>%
  count(positivo) %>%
  mutate(prop = n / sum(n) * 100) %>%
  filter(positivo) %>%
  select(-positivo) %>%
  round_cols()
```

```{r}
df_jat %>%
  select(respondent_id, sexo, matches("^L\\d.*?(_num)")) %>%
  pivot_longer(cols = starts_with("L")) %>%
  na.omit() %>%
  mutate(positivo = value >= 3) %>%
  group_by(name, sexo) %>%
  count(positivo) %>%
  mutate(prop = n / sum(n) * 100) %>%
  filter(positivo) %>%
  select(-positivo, -n) %>%
  pivot_wider(names_from = sexo, values_from = prop) %>%
  round_cols()
```

```{r}
df_jat %>%
  select(respondent_id, periodo, matches("^L\\d.*?(_num)")) %>%
  pivot_longer(cols = starts_with("L")) %>%
  na.omit() %>%
  mutate(positivo = value >= 3) %>%
  group_by(name, periodo) %>%
  count(positivo) %>%
  mutate(prop = n / sum(n) * 100) %>%
  filter(positivo) %>%
  select(-positivo, -n) %>%
  pivot_wider(names_from = periodo, values_from = prop) %>%
  round_cols()
```


## Classes
```{r}
df_jat %>%
  count(periodo)
```


```{r}
sum(df_jat$continua_estudiando) / nrow(df_jat) * 100

# By State and Gender
map(group_cols, function(group_col) {
  df_jat %>%
    group_by(across(group_col)) %>%
    summarise(
      n_studying = sum(continua_estudiando),
      n_total = n(),
      pct = mean(continua_estudiando) * 100
    )
  df_jat %>%
    group_by(across(all_of(group_col))) %>%
    filter(continua_estudiando == 1) %>%
    count(nivel_actual_estudios, name = "n_total") %>%
    mutate(pct = n_total / sum(n_total) * 100)
})

# Study levels among those currently studying
df_jat %>%
  filter(continua_estudiando == 1) %>%
  count(nivel_actual_estudios)

#
```

## Participación red
```{r}
df_jat %>% 
  count(participacion_red) %>% 
  na.omit() %>% 
  mutate(prop = round(n / sum(n) * 100, 2)) %>% 
  set_names(c("Participación en la Red", "n", "%"))
```


```{r}
responses <- nrow(df_jat)
df_jat %>%
  select(c("respondent_id", "participacion_red"), starts_with("contacto")) %>%
  mutate(contacto_07 = ifelse(is.na(contacto_07), contacto_07, "Con otros")) %>%
  pivot_longer(
    cols = starts_with("contacto"),
    names_to = "name",
    values_to = "contacto"
  ) %>%
  na.omit() %>%
  count(participacion_red, contacto, sort = TRUE) %>%
  mutate(prop = round(n / responses * 100, 2))
```